"""add Announcement table

Revision ID: 3b4cb540a5b0
Revises: f725f2e626b8
Create Date: 2023-07-29 18:17:34.487502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4cb540a5b0'
down_revision = '9f9715fd3e89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
